-- ASYQ ARENA Strong Edition — schema for Supabase
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text not null default 'Мерген',
  xp integer not null default 0,
  best_knocked integer not null default 0,
  best_accuracy integer not null default 0,
  completed jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);
create table if not exists public.results (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null,
  knocked integer not null,
  throws integer not null,
  accuracy integer not null,
  won boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;
alter table public.results enable row level security;
create policy "own profile read" on public.profiles for select using (auth.uid() = id);
create policy "own profile insert" on public.profiles for insert with check (auth.uid() = id);
create policy "own profile update" on public.profiles for update using (auth.uid() = id);
create policy "own results read" on public.results for select using (auth.uid() = user_id);
create policy "own results insert" on public.results for insert with check (auth.uid() = user_id);
